r"""
Hub registration store: maps laptop name -> registration token.
Persisted to %APPDATA%\RemoteControl\hub_registrations.json.

Tokens are 32-hex-char (128-bit) values generated by the Hub admin UI and
displayed once. Constant-time comparison on verify.
"""
from __future__ import annotations

import datetime as dt
import hmac
import json
import logging
import secrets
import threading
from dataclasses import dataclass, field
from pathlib import Path

from app.shared import config

logger = logging.getLogger(__name__)


@dataclass
class Registration:
    name: str
    token: str
    created_iso: str = ""
    last_seen_iso: str = ""

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "token": self.token,
            "created_iso": self.created_iso,
            "last_seen_iso": self.last_seen_iso,
        }


class HubRegistry:
    """Thread-safe registration store backed by a JSON file."""

    def __init__(self, path: Path | None = None) -> None:
        self._path = path or (config.appdata_dir() / "hub_registrations.json")
        self._lock = threading.RLock()
        self._regs: dict[str, Registration] = {}
        self._load()

    # ---------- public ----------

    def names(self) -> list[str]:
        with self._lock:
            return sorted(self._regs.keys())

    def get(self, name: str) -> Registration | None:
        with self._lock:
            return self._regs.get(self._key(name))

    def add(self, name: str) -> Registration:
        """Generate a new token for `name` (overwriting any existing one)."""
        token = secrets.token_hex(16)   # 32 hex chars = 128 bits
        reg = Registration(
            name=name.strip(),
            token=token,
            created_iso=dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        )
        with self._lock:
            self._regs[self._key(name)] = reg
            self._save_locked()
        return reg

    def remove(self, name: str) -> bool:
        with self._lock:
            removed = self._regs.pop(self._key(name), None)
            if removed is not None:
                self._save_locked()
                return True
            return False

    def verify(self, name: str, token: str) -> bool:
        with self._lock:
            reg = self._regs.get(self._key(name))
        if reg is None:
            return False
        return hmac.compare_digest(reg.token, token)

    def mark_seen(self, name: str) -> None:
        with self._lock:
            reg = self._regs.get(self._key(name))
            if reg is None:
                return
            reg.last_seen_iso = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
            self._save_locked()

    # ---------- internal ----------

    @staticmethod
    def _key(name: str) -> str:
        return name.strip().lower()

    def _load(self) -> None:
        if not self._path.exists():
            return
        try:
            data = json.loads(self._path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            logger.warning("hub registry file unreadable: %s", self._path)
            return
        if not isinstance(data, dict):
            return
        for key, entry in data.items():
            if not isinstance(entry, dict):
                continue
            try:
                reg = Registration(
                    name=str(entry.get("name", key)),
                    token=str(entry.get("token", "")),
                    created_iso=str(entry.get("created_iso", "")),
                    last_seen_iso=str(entry.get("last_seen_iso", "")),
                )
            except (TypeError, ValueError):
                continue
            if reg.token:
                self._regs[self._key(reg.name)] = reg

    def _save_locked(self) -> None:
        payload = {self._key(r.name): r.to_dict() for r in self._regs.values()}
        tmp = self._path.with_suffix(".tmp")
        try:
            tmp.write_text(json.dumps(payload, indent=2), encoding="utf-8")
            tmp.replace(self._path)
        except OSError:
            logger.exception("failed to write hub registry %s", self._path)

